ds4dm/Tulip.jl

Project.toml, src/MOI_wrapper.jl, src/Model/API/api.jl, src/Model/Model.jl, src/Model/pbdata.jl, src/Model/standardform.jl, src/Solvers/HSDSolver/HSDSolver.jl, src/Tulip.jl, src/bounds.jl, src/status.jl, test/MOI_wrapper.jl, test/Model/pbdata.jl, test/Solvers/HSD.jl, test/runtests.jl
Provides an interface to MOI.
Quick list of supported features:
* Linear objective & constraints
* Adding and deleting constraints
* Querying primal / dual solutions after solving
At this stage, it's highly likely that there are (several) bugs in the interface, and some features remain unsupported.
=> MOI wrapper

src/Solvers/HSDSolver/HSDSolver.jl
This will catch common/expected exceptions/error during the optimization.
In this case, the optimization is stopped and the corresponding status is returned.
Exceptions that are now handled:
* `PosDefException` while computing a factorization => `Trm_NumericalProblem`
* `SingularException` while solving a linear system => `Trm_NumericalProblem`
* `OutOfMemoryError` while forming the factor => `Trm_MemoryLimit`
* `InterruptException` => `Trm_Unknown`
Other types of errors are (currently) not expected, and will be re-throwned by the `catch` block.
=> Exceptions handling during optimization

.travis.yml, NEWS.md, Project.toml, src/MOI_wrapper.jl, src/Model/Model.jl, src/env.jl, test/MOI_wrapper.jl
* Add support for `MOI.NumberOfThreads`
* Check result index
=> Support for MOI 0.9.5

Project.toml, docs/src/man/linear_solvers.md, src/LinearAlgebra/LinearSolvers/LDLF.jl, src/LinearAlgebra/LinearSolvers/LinearSolvers.jl
Adds support for [LDLFactorizations.jl](https://github.com/JuliaSmoothOptimizers/LDLFactorizations.jl) as a backend for linear solvers.
This is the default choice for sparse matrices whose numerical precision cannot be handled by SuiteSparse, i.e., anything other than Float32/Float64.
=> LDLFactorizations support

test/Interfaces/MOI_wrapper.jl
This test will be added in MOI v0.9.14.
Closes https://github.com/ds4dm/Tulip.jl/issues/49
=> Exclude solve_func_vectoraffine_nonneg

src/Core/problemData.jl, test/Core/problemData.jl
=> Fix index update after row/column deletion

Project.toml, docs/src/manual/linear_systems.md, docs/src/reference/kkt_solvers.md, src/KKTSolver/KKTSolver.jl, src/KKTSolver/krylov.jl, test/KKTSolver/KKTSolver.jl, test/KKTSolver/krylov.jl
cc @amontoison
This PR introduces some infrastructure for Krylov-based linear solvers.
There are no Krylov-specific algorithmic modifications to the IPM at this point.
TODO:
Currently, a Krylov solver can be selected as follows:
```julia
model.params.KKTOptions = Tulip.KKT.SolverOptions(
Tulip.KKT.KrylovPDSolver,       # Solve the normal equations system with a Krylov method
method=Tulip.KKT.Krylov.minres  # Select the Krylov method
)
```
the syntax also allows for passing a callback:
```julia
model.params.KKTOptions = Tulip.KKT.SolverOptions(
Tulip.KKT.KrylovPDSolver,       # Solve the normal equations system with a Krylov method
method=(A, b) -> Tulip.KKT.Krylov.cg(A, b)  # "custom" Krylov method
)
```
=> Initial infrastructure for Krylov-based linear solvers

examples/optimal_other_type.jl, src/KKT/ldlfact.jl, test/examples.jl, test/runtests.jl
Still needs tests, addresses in part the issue observed in https://github.com/ds4dm/Tulip.jl/issues/64
=> Type-generic S matrix in LDL factorization

src/problemData.jl, test/Core/problemData.jl
Adds checks on new rows/columns, namely:
* zero coefficients are filtered out
* an error is thrown if a coefficient is not finite
It also fixes a bug in `add_variable!` that had somehow gone undetected.
Thanks @salomonl for bringing this to light!
Closes #77 
cc @amontoison
=> Filter out explicit zeros in new rows/columns

src/KKT/cholmod.jl
=> Improve the linear solver CholmodSQD

test/Project.toml
No compat was causing Pkg to install an earlier version in tests with `MOI#master` for some reason.
=> Fix compat of Convex.jl in tests

Project.toml, src/Presolve/Presolve.jl, src/Presolve/empty_column.jl, src/Presolve/empty_row.jl, src/Tulip.jl, src/model.jl, test/Presolve/empty_row.jl, test/runtests.jl
=> Add primal and dual tolerances in presolve

Project.toml, src/KKT/Krylov/sqd.jl, test/Project.toml
`solver.x` and `solver.y` are the solutions for all solvers now.
=> Hotfix for the next release of Krylov.jl

Project.toml, src/Tulip.jl, test/runtests.jl
@mtanneau is it possible to get a new release? This is blocking https://github.com/SciML/GalacticOptim.jl/pull/218 (via a dependency in NOMAD.jl).
=> Prep for v0.9.3

src/KKT/LDLFactorizations/ldlfact.jl
This was discussed at
https://discourse.julialang.org/t/why-does-jet-give-these-runtime-dispatch-detected-lines-for-some-ldlfactorizations-calls-in-tulip/79583
In that discussion, aviatesk pointed out that
LDLFactorizations.LDLFactorization is missing type parameters.
The reason for that is that the type parameters were missing in the
definition of the LDLFactSolver struct in its field F, so I added
them.
=> KKT/LDLFactorizations: fix runtime dispatch as reported by JET

src/IPM/HSD/HSD.jl, src/IPM/HSD/step.jl, src/IPM/MPC/MPC.jl, src/IPM/MPC/step.jl, src/IPM/ipmdata.jl
https://docs.julialang.org/en/v1.8/manual/performance-tips/#More-dots:-Fuse-vectorized-operations
I ran a benchmark with Tulip.Optimizer{MultiFloats.Float64x8}(): there was no speed improvement with this benchmark, but the reduction in allocations was significant. This would translate to less GC time in a more complex application, I guess.
State on master (ae81ed857f96f1dbe279664f8b5504621880c61e):
```
BenchmarkTools.Trial: 16 samples with 1 evaluation.
Range (min … max):  308.254 ms … 322.011 ms  ┊ GC (min … max): 0.00% … 2.00%
Time  (median):     309.053 ms               ┊ GC (median):    0.00%
Time  (mean ± σ):   312.932 ms ±   6.263 ms  ┊ GC (mean ± σ):  0.64% ± 0.95%
▁▄▄▁                                                       █ …
```
=> performance: fuse more vectorized operations

src/Tulip.jl
xref https://discourse.julialang.org/t/missing-relocatability-of-tulip/94886
=> Read version number from Project.toml during precompilation, fixes #131.

src/Interfaces/tulip_julia_api.jl
From https://ds4dm.github.io/Tulip.jl/dev/reference/attributes/
> SolutionTime	Float64	Solution time, in seconds
=> Allow querying `SolutionTime` attribute (mentioned in the docs, but so far unimplemented)

src/IPM/HSD/step.jl
Since the `KKT.solve!()` is typically one of the more expensive parts of a Newton step computation, we should account for the ~20% of calls and runtime that are currently unreported.
=> Count another location of `KKT.solve!()` call in the final stats (previously unreported).

src/Interfaces/MOI/MOI_wrapper.jl, src/Interfaces/MOI/attributes.jl, src/Interfaces/MOI/constraints.jl, src/Interfaces/MOI/objective.jl, src/Interfaces/MOI/variables.jl, test/Interfaces/MOI_wrapper.jl
Closes https://github.com/ds4dm/Tulip.jl/issues/130
=> Fix missing MOI methods and update tests

Project.toml
Version v0.10.0 was never actually released https://github.com/JuliaRegistries/General/pull/122097 because it was tagged as a breaking release without a list of the breaking changes: https://github.com/ds4dm/Tulip.jl/commit/438a77b7e08b9233365603c1089cf4002e3f507c#commitcomment-150774778
I don't see anything actually breaking https://github.com/ds4dm/Tulip.jl/compare/v0.9.6...master so I think you can actually release v0.9.7
=> Prep for v0.9.7
